import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parse } from 'csv-parse/sync';

type CsvRow = Record<string, string>;

type VariableDefinition = {
  variable: string;
  title: string;
  definition: string;
};

const CSV_PATH = resolve(process.cwd(), 'fdicapi/fdic-reference-variable-definitions.csv');
const OUTPUT_PATH = resolve(process.cwd(), 'lib/data/variable-definitions.ts');

const sanitize = (value: string) =>
  value
    .replace(/\r?\n|\r/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

function main() {
  const csv = readFileSync(CSV_PATH, 'utf8');
  const rows = parse(csv, {
    columns: true,
    skip_empty_lines: true,
    cast: (value: string) => value.trim(),
  }) as CsvRow[];

  const items: VariableDefinition[] = rows
    .map((row) => ({
      variable: row.Variable ?? row.variable ?? '',
      title: row.Title ?? row.title ?? '',
      definition: sanitize(row.Definition ?? row.definition ?? ''),
    }))
    .filter((item) => item.variable.length > 0)
    .sort((a, b) => a.variable.localeCompare(b.variable));

  const banner = `// This file is auto-generated by scripts/build-variable-reference.ts\n// Do not edit this file directly.\n`;

  const body = `${banner}export type VariableDefinition = {
  variable: string;
  title: string;
  definition: string;
};

export const variableDefinitions: VariableDefinition[] = ${JSON.stringify(items, null, 2)};
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, body);
  // eslint-disable-next-line no-console -- useful script output
  console.log(`Wrote ${items.length} variable definitions to ${OUTPUT_PATH}`);
}

main();
